# Generated by Django 5.2.4 on 2025-07-05 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the travel listing', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the listing')),
                ('location', models.CharField(help_text='Location of the travel destination', max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Listing',
                'verbose_name_plural': 'Travel Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
