# Generated by Django 5.2.5 on 2025-08-16 01:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_amenities_listing_availability_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="ETB", help_text="Payment currency", max_length=3
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("chapa", "Chapa"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                        ],
                        default="chapa",
                        help_text="Payment method used",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "chapa_tx_ref",
                    models.CharField(
                        blank=True,
                        help_text="Chapa transaction reference",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "chapa_checkout_url",
                    models.URLField(
                        blank=True, help_text="Chapa checkout URL", null=True
                    ),
                ),
                (
                    "chapa_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Chapa transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="External payment reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, help_text="Raw gateway response data", null=True
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Reason for payment failure", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when payment was completed",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        help_text="Associated booking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="listings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chapa_tx_ref"], name="listings_pa_chapa_t_b99a2d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="listings_pa_status_98563c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="listings_pa_created_5fdebf_idx"
                    ),
                ],
            },
        ),
    ]
